增加wsl下emacs在服务器端启动

diff --git a/wsl/bin/emacsd b/wsl/bin/emacsd
--- a/wsl/bin/emacsd
+++ b/wsl/bin/emacsd
@@ -1,96 +1,157 @@
 #!/bin/sh
 
 ### BEGIN INIT INFO
-# Provides:          emacsd
-# Required-Start:    $remote_fs $syslog
-# Required-Stop:     $remote_fs $syslog
+# Provides:          emacs
 # Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: Start emacsd at boot time
-# Description:       Enable service provided by daemon.
+# Default-Stop:      S 0 1 6
+# Description:       This file should be placed in /etc/init.d.
 ### END INIT INFO
 
-# Local Settings
-
-PATH=/usr/local/bin:/usr/bin:/bin
-
+#change this
+#USERNAME=YourUserName
+USERNAME=`id sunday -un`
+eval USERHOME=~$USERNAME
+DESC="Run the emacs daemon."
+NAME=emacs
+#change this
+#DAEMON=/opt/emacs23/bin/$NAME
 DAEMON=`which emacs`
+DAEMON_ARGS="--daemon"
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
+#change this
+#EMACSCLIENT=/opt/emacs23/bin/emacsclient
 EMACSCLIENT=`which emacsclient`
-EMACSD_UID=`id -u`
-SOCKET_FILE="/tmp/emacs${EMACSD_UID}/server"
 
-# EE code
-EE_EMACS_NOT_FOUND=1
-EE_INVALID_OPTION=2
-EE_EMACS_FAIL_TO_START=3
-EE_EMACS_FAIL_TO_STOP=4
+EVALEXIT="(progn (kill-emacs))"
 
-# Real code begins here
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
 
-if [ -z "$DAEMON" ]
-then
-    log_daemon_msg "Error: Emacs not found. emacsd will now exit."
-    exit $EE_EMACS_NOT_FOUND
-fi
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
-# TODO Start emacs as normal user "emacsd" or "daemon"
-#emacs run under this uid
+# Load the VERBOSE setting and other rcS variables
+[ -f /etc/default/rcS ] && . /etc/default/rcS
 
-if [ "$1" = "start" ]
-then
-    #check whether already started
-    if [ -e "$SOCKET_FILE" ]
-    then
-        echo "Error: emacsd already started."
-        exit $EE_EMACSD_ALREADY_STARTED
-    fi
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
+. /lib/lsb/init-functions
 
-    echo "Start $DAEMON daemon ..."
-    $DAEMON --daemon
+PATH=/usr/local/bin:/usr/bin:/bin:/sbin
 
-    if [ "$?" -eq 0 ]
-    then
-        echo "emacsd is up."
-        exit 0
-    else
-        echo "Error: emacsd failed to start."
-        exit $EE_EMACS_FAIL_TO_START
-    fi
-fi
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+	  # Return
+	  #   0 if daemon has been started
+	  #   1 if daemon was already running
+	  #   2 if daemon could not be started
+	  start-stop-daemon -c $USERNAME -d $USERHOME --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+		    || return 1
+	  start-stop-daemon -c $USERNAME -d $USERHOME --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+		                  $DAEMON_ARGS \
+		    || return 2
+	  # Add code here, if necessary, that waits for the process to be ready
+	  # to handle requests from services started subsequently which depend
+	  # on this one.  As a last resort, sleep for some time.
+}
 
-if [ "$1" = "stop" ]
-then
-    #options="-s $SOCKET_FILE"
-    options=""
-    lispcode="(save-buffers-kill-terminal)"
-    $EMACSCLIENT $options --eval $lispcode
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+    $EMACSCLIENT --eval "$EVALEXIT"
+	  # Return
+	  #   0 if daemon has been stopped
+	  #   1 if daemon was already stopped
+	  #   2 if daemon could not be stopped
+	  #   other if a failure occurred
+	  start-stop-daemon --stop --quiet --retry=TERM/120/KILL/5 --pidfile $PIDFILE --name $NAME
+	  RETVAL="$?"
+	  [ "$RETVAL" = 2 ] && return 2
+	  # Wait for children to finish too if this is a daemon that forks
+	  # and if the daemon is only ever run from this initscript.
+	  # If the above conditions are not satisfied then add some other code
+	  # that waits for the process to drop all resources that could be
+	  # needed by services started subsequently.  A last resort is to
+	  # sleep for some time.
+	  start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	  [ "$?" = 2 ] && return 2
+	  # Many daemons don't delete their pidfiles when they exit.
+	  rm -f $PIDFILE
+	  return "$RETVAL"
+}
 
-    if [ "$?" -eq 0 ]
-    then
-        echo "emacsd is down."
-        exit 0
-    else
-        echo "Error: emacsd failed to stop."
-        exit $EE_EMACS_FAIL_TO_STOP
-    fi
-    exit 0
-fi
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+	  #
+	  # If the daemon can reload its configuration without
+	  # restarting (for example, when it is sent a SIGHUP),
+	  # then implement that here.
+	  #
+	  start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+	  return 0
+}
 
-if [ "$1" = "restart" ] || [ "$1" = "force-reload" ]
-then
-    if [ -e "$SOCKET_FILE" ]
-    then
-        $0 stop
-    fi
-    $0 start
-    exit $?
-fi
+case "$1" in
+    start)
+	      [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	      do_start
+	      case "$?" in
+		        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	      esac
+	      ;;
+    stop)
+	      [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	      do_stop
+	      case "$?" in
+		        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	      esac
+	      ;;
+    #reload|force-reload)
+	  #
+	  # If do_reload() is not implemented then leave this commented out
+	  # and leave 'force-reload' as an alias for 'restart'.
+	  #
+	  #log_daemon_msg "Reloading $DESC" "$NAME"
+	  #do_reload
+	  #log_end_msg $?
+	  #;;
+    restart|force-reload)
+	      #
+	      # If the "reload" option is implemented then remove the
+	      # 'force-reload' alias
+	      #
+	      log_daemon_msg "Restarting $DESC" "$NAME"
+	      do_stop
+	      case "$?" in
+	          0|1)
+		            do_start
+		            case "$?" in
+			              0) log_end_msg 0 ;;
+			              1) log_end_msg 1 ;; # Old process is still running
+			              *) log_end_msg 1 ;; # Failed to start
+		            esac
+		            ;;
+	          *)
+	  	          # Failed to stop
+		            log_end_msg 1
+		            ;;
+	      esac
+	      ;;
+    *)
+	      #echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+	      echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
+	      exit 3
+	      ;;
+esac
 
-echo "Usage: /etc/init.d/emacsd {start|stop|restart|force-reload}"
-if ! [ -z "$1" ]
-then
-    echo "No such option:" $*
-    exit $EE_INVALID_OPTION
-fi
-
-exit 0
+:
